name: Run autoindex
description: GitHub Action for the autoindex CLI

inputs:
  version:
    description: The autoindex version
    required: false
    default: latest
  args:
    description: Arguments to pass to autoindex
    required: false

runs:
  using: composite
  steps:
    - name: Install
      run: go install github.com/go-autoindex/cli/cmd/autoindex@'${{ inputs.version }}'
      shell: sh
    - name: Run
      run: '"$(go env GOPATH)"/bin/autoindex $AUTOINDEX_ARGS'
      env:
        AUTOINDEX_ARGS: ${{ inputs.args }}
      shell: sh

branding:
  icon: book-open
  color: white
